# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c

before_install:
- if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then exit 0; fi
- bash setup.sh
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/pietrocaselani/Trakt-Swift.git"
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./ci/master.sh; elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./ci/pull_request.sh; fi