# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c

before_install:
- bash setup.sh
script:
- bundle exec fastlane lint
